
evaluation:
  method: exec_accuracy
  num_samples: 30
  num_few_shot: 5
  model:
    name: GPT_forward
    batch_size: 20
    gpt_config:
      model: text-davinci-002
      temperature: 0.7
      max_tokens: 200
      top_p: 1.0
      frequency_penalty: 0.0
      presence_penalty: 0.0
